### ISSUE TITLE
Add code-based documentation

### ISSUE THREAD

**Issue by wintondeshong** [AndcultureCode/AndcultureCode.Scss.Grid#5]
Now that I've added tooling with documentation generation. Any code comments will get bubbled up and automatically compiled in the repo's github pages. 

This issue is to do an initial pass of documenting the actors available in the repository.

**Comment by wintondeshong** [comment]
@zachmccleaf and/ or @dylanjustice - either of you interested in taking this on given your previous involvement in the repository?

**Comment by wintondeshong** [comment]
@all-contributors please add @wintondeshong for code, documentation and maintenance

**Comment by wintondeshong** [comment]
@all-contributors please add @zachmccleaf for code

**Comment by dylanjustice** [comment]
@wintondeshong Can do!
